server:
  port: 7788
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.124.3:8841,192.168.124.3:8842,192.168.124.3:8843
        group: CLUSTER_GROUP
        namespace: 3ab3edcf-ec35-42cb-aac7-f93313212ffb
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: route-customer-1
        uri: http://localhost:9001        # 常规方式
        predicates:
        -  Path=/user/config/getFlag      # 断言1 注意：Path路径必须要和路由服务路径一致，否则访问不到
        -  Query=id                         # 断言2 按照断言顺序依次执行
        filters:
        - StripPrefix=2                   # 截取uri中前n级的前缀
      - id: route-customer-before
        uri: lb://nacos-customer          # 负载方式
        predicates:
        - Before=2021-12-03T09:10:00
      - id: route-customer-before
        uri: lb://nacos-customer          # 负载方式
        predicates:
        - Between=2021-12-03T09:20:47.789-07:00, 2021-12-03T09:30:47.789-07:00


MDB:
  ribbon:
    NFLoadBalancerRuleClassName: com.hexiaofei.mygateway.balancerRule.MyBalancerRule
