package com.hexiaofei.nacoscustomer.dao.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hexiaofei.pubapi.entity.Employees;
import com.hexiaofei.pubapi.entity.EmployeesExample.Criteria;
import com.hexiaofei.pubapi.entity.EmployeesExample.Criterion;
import com.hexiaofei.pubapi.entity.EmployeesExample;
import java.util.List;
import java.util.Map;

public class EmployeesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    public String countByExample(EmployeesExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("employees");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    public String deleteByExample(EmployeesExample example) {
        BEGIN();
        DELETE_FROM("employees");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    public String insertSelective(Employees record) {
        BEGIN();
        INSERT_INTO("employees");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getFname() != null) {
            VALUES("fname", "#{fname,jdbcType=VARCHAR}");
        }
        
        if (record.getLname() != null) {
            VALUES("lname", "#{lname,jdbcType=VARCHAR}");
        }
        
        if (record.getHired() != null) {
            VALUES("hired", "#{hired,jdbcType=DATE}");
        }
        
        if (record.getSeparated() != null) {
            VALUES("separated", "#{separated,jdbcType=DATE}");
        }
        
        if (record.getJob_code() != null) {
            VALUES("job_code", "#{job_code,jdbcType=INTEGER}");
        }
        
        if (record.getStore_id() != null) {
            VALUES("store_id", "#{store_id,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    public String selectByExample(EmployeesExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("fname");
        SELECT("lname");
        SELECT("hired");
        SELECT("separated");
        SELECT("job_code");
        SELECT("store_id");
        FROM("employees");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Employees record = (Employees) parameter.get("record");
        EmployeesExample example = (EmployeesExample) parameter.get("example");
        
        BEGIN();
        UPDATE("employees");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getFname() != null) {
            SET("fname = #{record.fname,jdbcType=VARCHAR}");
        }
        
        if (record.getLname() != null) {
            SET("lname = #{record.lname,jdbcType=VARCHAR}");
        }
        
        if (record.getHired() != null) {
            SET("hired = #{record.hired,jdbcType=DATE}");
        }
        
        if (record.getSeparated() != null) {
            SET("separated = #{record.separated,jdbcType=DATE}");
        }
        
        if (record.getJob_code() != null) {
            SET("job_code = #{record.job_code,jdbcType=INTEGER}");
        }
        
        if (record.getStore_id() != null) {
            SET("store_id = #{record.store_id,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("employees");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("fname = #{record.fname,jdbcType=VARCHAR}");
        SET("lname = #{record.lname,jdbcType=VARCHAR}");
        SET("hired = #{record.hired,jdbcType=DATE}");
        SET("separated = #{record.separated,jdbcType=DATE}");
        SET("job_code = #{record.job_code,jdbcType=INTEGER}");
        SET("store_id = #{record.store_id,jdbcType=INTEGER}");
        
        EmployeesExample example = (EmployeesExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    protected void applyWhere(EmployeesExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}