package com.hexiaofei.nacoscustomer.dao.mapper;

import com.hexiaofei.pubapi.entity.Employees;
import com.hexiaofei.pubapi.entity.EmployeesExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Repository
public interface EmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @SelectProvider(type=EmployeesSqlProvider.class, method="countByExample")
    int countByExample(EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @DeleteProvider(type=EmployeesSqlProvider.class, method="deleteByExample")
    int deleteByExample(EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @Insert({
        "insert into employees (id, fname, ",
        "lname, hired, separated, ",
        "job_code, store_id)",
        "values (#{id,jdbcType=INTEGER}, #{fname,jdbcType=VARCHAR}, ",
        "#{lname,jdbcType=VARCHAR}, #{hired,jdbcType=DATE}, #{separated,jdbcType=DATE}, ",
        "#{job_code,jdbcType=INTEGER}, #{store_id,jdbcType=INTEGER})"
    })
    int insert(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @InsertProvider(type=EmployeesSqlProvider.class, method="insertSelective")
    int insertSelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @SelectProvider(type=EmployeesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="fname", property="fname", jdbcType=JdbcType.VARCHAR),
        @Result(column="lname", property="lname", jdbcType=JdbcType.VARCHAR),
        @Result(column="hired", property="hired", jdbcType=JdbcType.DATE),
        @Result(column="separated", property="separated", jdbcType=JdbcType.DATE),
        @Result(column="job_code", property="job_code", jdbcType=JdbcType.INTEGER),
        @Result(column="store_id", property="store_id", jdbcType=JdbcType.INTEGER)
    })
    List<Employees> selectByExample(EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @UpdateProvider(type=EmployeesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Employees record, @Param("example") EmployeesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbggenerated Sun Dec 19 11:49:22 CST 2021
     */
    @UpdateProvider(type=EmployeesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Employees record, @Param("example") EmployeesExample example);
}